CREATE DATABASE IF NOT EXISTS Eben-Ezer;

CREATE TABLE EMPLEADOS (
    empleado_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL, 
    ESADMIN BOOLEAN NOT NULL, 
    PASSWORD VARCHAR(25) NOT NULL
);

CREATE TABLE VENTAS (
    venta_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sale_date DATE NOT NULL,
    total_price FLOAT NOT NULL,
    id_empleado INT NOT NULL,
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADOS(empleado_id)
);

CREATE TABLE PRODUCTOS (
    producto_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL, 
    MARCA VARCHAR(25) NOT NULL,
    PRICE FLOAT NOT NULL, 
    STOCK INT NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);




-- INSERT DATA --

INSERT INTO EMPLEADOS (NAME, ESADMIN, PASSWORD) VALUES ('admin', true, 'password'), ('elkasiques', false, 'elkasiques');

INSERT INTO PRODUCTOS (NAME, MARCA, PRICE, STOCK, DESCRIPTION) VALUES ("FOCO", "RADIOSACK", 22.5, 100, "FOCO DE 10W ULTRA AHORRATIVO."), ("HAMBURGUESA", "ELKASIQUES", 45.0, 10, "HAMBURGUESAS UTRA RICAS.");
